// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prova_crud.context;

#nullable disable

namespace prova_crud.Migrations
{
    [DbContext(typeof(ImovelContext))]
    [Migration("20240916230754_ImoveisTable")]
    partial class ImoveisTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("prova_crud.entities.Imovel", b =>
                {
                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("dataCompra")
                        .HasColumnType("datetime2");

                    b.Property<string>("endereco")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Descricao");

                    b.ToTable("Imoveis");
                });
#pragma warning restore 612, 618
        }
    }
}
